/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/authentication',
        'getting-started/concepts',
      ],
    },
    {
      type: 'category',
      label: 'REST API',
      link: {
        type: 'generated-index',
        title: 'REST API Reference',
        description:
          'Complete reference for the Comms Platform REST API. Use the built-in Try It console to test endpoints directly from the docs.',
        slug: '/rest-apis',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'rest-apis',
        },
      ],
    },
    {
      type: 'category',
      label: 'Event-Driven (Kafka)',
      link: {
        type: 'generated-index',
        title: 'Event-Driven Architecture',
        description:
          'Kafka topics and event schemas for real-time integration with the Comms Platform.',
        slug: '/events-kafka',
      },
      items: [
        'events-kafka/overview',
        'events-kafka/topology',
        'events-kafka/event-schemas',
      ],
    },
    {
      type: 'category',
      label: 'File Integrations',
      link: {
        type: 'generated-index',
        title: 'File-Based Integrations',
        description:
          'Bulk message delivery and report retrieval via file-based SFTP integrations.',
        slug: '/file-transfers',
      },
      items: [
        'file-transfers/overview',
        'file-transfers/batch-messages',
        'file-transfers/delivery-reports',
      ],
    },
  ],
};

module.exports = sidebars;
